// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obrbuswryzikkftniujc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9icmJ1c3dyeXppa2tmdG5pdWpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NDI0NTEsImV4cCI6MjA2MDUxODQ1MX0.Ih_QFrG-hpP5JS92qfiNsNewqJigQ4N9-kF45nX8XWw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);